theme = "BitsOfInformationTheme"
baseurl = ""
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
title = "Bits of Information"
MetaDataFormat = "toml"
[indexes]
  category = "categories"
  tag = "tags"
[author]
  name = "Sam"
